name: vpn
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  gap: ^3.0.1
  svg_flutter:
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  csv: ^6.0.0
  lottie: ^3.3.1
  flutter_animate: ^4.5.0
  bounce: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.12.1
  firebase_remote_config: ^5.4.2
  shimmer: 3.0.0
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/


flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:    